# Generated by Django 3.1.7 on 2021-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
