# Generated by Django 3.1.7 on 2021-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=10)),
                ('business_num', models.IntegerField(max_length=15)),
            ],
        ),
    ]
