# Generated by Django 3.1.7 on 2021-04-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
