# Generated by Django 3.1.7 on 2021-04-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_cmd_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmd_answer',
            name='Car_num',
        ),
        migrations.AddField(
            model_name='cmd_answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pybo.cmd_information'),
            preserve_default=False,
        ),
    ]
