# Generated by Django 3.1.7 on 2021-04-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20210429_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmd_answer',
            name='question',
        ),
        migrations.AddField(
            model_name='cmd_answer',
            name='cmd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pybo.cmd_information'),
        ),
    ]
