# Generated by Django 3.1.7 on 2021-05-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20210510_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_apply',
            old_name='business_num',
            new_name='assign_num',
        ),
    ]
