# Generated by Django 3.1.7 on 2021-04-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_answer_cmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmd_information',
            old_name='bussiness_num',
            new_name='cmd_bussiness_num',
        ),
    ]
