# Generated by Django 3.1.7 on 2021-04-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20210428_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmd_information',
            name='author',
        ),
        migrations.AddField(
            model_name='question',
            name='position_end',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='position_start',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer_CMD',
        ),
        migrations.DeleteModel(
            name='CMD_Information',
        ),
    ]
