# Generated by Django 3.1.7 on 2021-04-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0007_auto_20210428_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMD_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_num', models.CharField(max_length=15)),
                ('Car_variety', models.CharField(max_length=10)),
                ('Car_manager', models.CharField(max_length=10)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('position_start', models.TextField()),
                ('position_end', models.TextField()),
                ('user_num', models.CharField(max_length=20, verbose_name='사번')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
