# Generated by Django 3.1.7 on 2021-04-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_cmd_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmd_information',
            name='bussiness_num',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
